### ISSUE TITLE
Maveo App Token missing

### ISSUE THREAD

**Issue by Gerudom** [TA2k/ioBroker.maveo#1]
Hallo,

was fehlt denn hier ?
iobroker Adapter fertig installiert und Credentials eingetragen. Im log folgendes

Woher kommt der Token etc. pp

maveo.0 | 2022-01-26 11:31:14.646 | error | {"message":"Missing Authentication Token"}
maveo.0 | 2022-01-26 11:31:14.645 | error | Error: Request failed with status code 403
maveo.0 | 2022-01-26 11:31:14.645 | error | https://api-cloud.nymea.io/users/devices/undefined

**Comment by TA2k** [comment]
Es werden anscheinend nicht korrekt die geräte erkannt.
Ich bräuchte ein debug log vom start auch gerne per mail
tombox2020@gmail.com

**Comment by Gerudom** [comment]
Wurde erledigt. Funktioniert nun nach der Überarbeitung des Adapters
